---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  members: {{ .Values.replicas }}
  type: ReplicaSet
  version: "{{ .Values.mongodbVersion }}"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodbUsername }} 
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ .Release.Name }}-mongodb-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: {{ .Release.Name }}-mongodb-scram-salt
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          nodeSelector:
            workload_type: mongo
          tolerations:
          - key: workload_type
            value: mongo
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "4"
                  memory: 8G
                requests:
                  cpu: 500m
                  memory: 2G
            - name: log-cleaner
              image: gcr.io/zencastr-prod/mongodb-log-cleaner:21fceb7
              volumeMounts:
              - name: logs-volume
                mountPath: /logs